import type { NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { Box, Typography, TextField, Button } from "@mui/material/";

import { signOutUser } from "../firebase/config";

import nookies from "nookies";

import { firebaseAdmin } from "../firebase/adminSDK";

const Home = ({ uid, email, name }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography component="h1" variant="h5" sx={{ mb: 2 }}>
          Welcome {name}
        </Typography>
        <Button variant="contained" href="/welcome">
          Go to welcome page
        </Button>

        <Button variant="contained" onClick={() => signOutUser()}>
          Sign out
        </Button>
      </main>
    </div>
  );
};

export const getServerSideProps = async (ctx: any) => {
  try {
    const cookies = nookies.get(ctx);

    const token = await firebaseAdmin.auth().verifyIdToken(cookies.token);

    console.log(token);
    // the user is authenticated!
    const { uid, email, name } = token;

    // FETCH STUFF HERE!!

    return {
      props: { uid, email, name: name || "" },
    };
  } catch (err) {
    console.log({ err });
    if (err) {
      return {
        redirect: {
          destination: "/login",
          permanent: false,
        },
      };
    }
    // ctx.res.writeHead(302, { Location: "/login" });
    // ctx.res.end();

    return { props: {} as never };
  }
};

export default Home;
